export const trendingItems = [
  {
    id: 't1',
    title: 'MacBook Air M1 (2020)',
    price: '$720',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=400&fit=crop&auto=format',
    badge: 'Trending',
  },
  {
    id: 't2',
    title: 'Calculus Textbook — Stewart 8th Ed.',
    price: '$25',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&h=400&fit=crop&auto=format',
    badge: 'Popular',
  },
];

export const trendingRide = {
  id: 'tr1',
  origin: 'NSU Campus',
  destination: 'Dhanmondi 27',
  time: 'Today · 5:30 PM',
  seats: '2 seats',
  fare: '$3',
};

export const featuredListings = [
  {
    product_id: 'fp1',
    title: 'MacBook Air M1 (2020)',
    price: 720,
    condition: 'Like New',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=400&fit=crop&auto=format',
    location: 'NSU Campus',
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    seller_name: 'Aiman Rahman',
    seller_id: 'user_f1',
    seller_rating: 4.9,
  },
  {
    product_id: 'fp2',
    title: 'Calculus Textbook — Stewart 8th Ed.',
    price: 25,
    condition: 'Good',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&h=400&fit=crop&auto=format',
    location: 'Dhanmondi',
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    seller_name: 'Sadia Islam',
    seller_id: 'user_f2',
    seller_rating: 4.7,
  },
  {
    product_id: 'fp3',
    title: 'IKEA Study Desk',
    price: 65,
    condition: 'Good',
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&h=400&fit=crop&auto=format',
    location: 'Bashundhara',
    created_at: new Date(Date.now() - 24 * 3600000).toISOString(),
    seller_name: 'Rifat Hasan',
    seller_id: 'user_f3',
    seller_rating: 4.8,
  },
  {
    product_id: 'fp4',
    title: 'Sony WH-1000XM4 Headphones',
    price: 190,
    condition: 'Like New',
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&h=400&fit=crop&auto=format',
    location: 'Gulshan',
    created_at: new Date(Date.now() - 72 * 3600000).toISOString(),
    seller_name: 'Nusrat Jahan',
    seller_id: 'user_f4',
    seller_rating: 5.0,
  },
];

export const campusRides = [
  {
    ride_id: 'fr1',
    driver_name: 'Rifat Hasan',
    driver_id: 'user_f3',
    driver_rating: 4.9,
    vehicle_details: 'Toyota Axio',
    fare_per_seat: 3,
    origin: 'NSU Campus',
    destination: 'Dhanmondi 27',
    date_time: new Date(Date.now() + 4 * 3600000).toISOString(),
    seats_available: 2,
    seats_total: 3,
  },
  {
    ride_id: 'fr2',
    driver_name: 'Sadia Islam',
    driver_id: 'user_f2',
    driver_rating: 4.7,
    vehicle_details: 'Honda Civic',
    fare_per_seat: 2,
    origin: 'Bashundhara Gate',
    destination: 'NSU Campus',
    date_time: new Date(Date.now() + 20 * 3600000).toISOString(),
    seats_available: 3,
    seats_total: 4,
  },
  {
    ride_id: 'fr3',
    driver_name: 'Aiman Rahman',
    driver_id: 'user_f1',
    driver_rating: 5.0,
    vehicle_details: 'Toyota Premio',
    fare_per_seat: 4,
    origin: 'NSU Campus',
    destination: 'Gulshan 2',
    date_time: new Date(Date.now() + 6 * 3600000).toISOString(),
    seats_available: 1,
    seats_total: 3,
  },
];

export const testimonials = [
  {
    name: 'Sadia Islam',
    dept: 'CSE, NSU',
    text: 'I sold my old textbooks in a day and picked up a study desk for half price. Life saver during finals.',
    avatar: null,
  },
  {
    name: 'Rifat Hasan',
    dept: 'BBA, NSU',
    text: 'Offering rides on my daily commute pays for my fuel. Made friends across departments too.',
    avatar: null,
  },
  {
    name: 'Nusrat Jahan',
    dept: 'EEE, NSU',
    text: 'The verified badges make it feel safe. I never worry about who I\'m meeting on campus.',
    avatar: null,
  },
];
